[package]
name = "guirs-style"
description = "Stylesheet language, cascade and transitions for guirs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
guirs-core.workspace = true
ahash.workspace = true
smallvec.workspace = true
